AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stack for sending emails via SES

Parameters:
  securityGroupIds:
    Type: String
    Default: sg-000000
  subnetIDs:
    Type: String
    Default: subnet-1,subnet-2

Resources:

  secretManagerSMTP:
    Type: AWS::SecretsManager::Secret
    Properties:
      # Name: 
      Description: Secret for SMTP.
      SecretString: '{"SMTP_PASS":"--SMTP-PASS--","SMTP_PORT":--SMTP-PORT--,"SMTP_SERVER":"--SMTP-SERVER--","SMTP_USER":"--SMTP-USER--"}'

  mailDeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: src/mailDeliveryFunction
      Runtime: python3.12
      Timeout: 5
      Policies:
        - AmazonSESFullAccess
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !GetAtt secretManagerSMTP.Id
      Environment:
        Variables:
          secretManagerArn: !GetAtt secretManagerSMTP.Id
      VpcConfig:
        SubnetIds: !Split [",", !Ref subnetIDs]
        SecurityGroupIds: !Ref securityGroupIds
  